// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Login {
  final int uid;
  final String email;
  final String hash;
  final String s5R82132Saltkey;
  final String s5R82132Auth;

  const Login({
    required this.uid,
    required this.email,
    required this.hash,
    required this.s5R82132Saltkey,
    required this.s5R82132Auth,
  });

  @override
  int get hashCode =>
      uid.hashCode ^
      email.hashCode ^
      hash.hashCode ^
      s5R82132Saltkey.hashCode ^
      s5R82132Auth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Login &&
          runtimeType == other.runtimeType &&
          uid == other.uid &&
          email == other.email &&
          hash == other.hash &&
          s5R82132Saltkey == other.s5R82132Saltkey &&
          s5R82132Auth == other.s5R82132Auth;
}
