[package]
name = "ci"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
reqwest = "0.12.2"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.115"
tokio = { version = "1.36.0", features = ["full"] }
