// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../client/community/dataobject.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `BbsCategoryLoader` is not used by any `pub` functions, thus it is ignored.

Future<List<BbsCategory>> bbsCategories({dynamic hint}) =>
    RustLib.instance.api.bbsCategories(hint: hint);

Future<ThreadPage> bbsThreadsList(
        {required String fid, required int page, dynamic hint}) =>
    RustLib.instance.api.bbsThreadsList(fid: fid, page: page, hint: hint);

Future<ThreadData> bbsThread(
        {required String tid, required int page, dynamic hint}) =>
    RustLib.instance.api.bbsThread(tid: tid, page: page, hint: hint);
