// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../client/user_center/dataobject.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<LoginState> login(
        {required String username, required String password, dynamic hint}) =>
    RustLib.instance.api
        .login(username: username, password: password, hint: hint);

Future<LoginState> reLogin({dynamic hint}) =>
    RustLib.instance.api.reLogin(hint: hint);

class LoginState {
  final bool empty;
  final bool error;
  final String errorMsg;
  final bool success;
  final Login login;

  const LoginState({
    required this.empty,
    required this.error,
    required this.errorMsg,
    required this.success,
    required this.login,
  });

  @override
  int get hashCode =>
      empty.hashCode ^
      error.hashCode ^
      errorMsg.hashCode ^
      success.hashCode ^
      login.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginState &&
          runtimeType == other.runtimeType &&
          empty == other.empty &&
          error == other.error &&
          errorMsg == other.errorMsg &&
          success == other.success &&
          login == other.login;
}
